/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LinguisticProcessingProgress.java
 *
 * Created on 14.03.2011, 9:46:40
 */

package ua.kiev.univ.ui;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import ua.kiev.univ.linguistics.ClusterizationResult;
import ua.kiev.univ.linguistics.Clusterizer;

/**
 *
 * @author taras
 */
public class LinguisticProcessingProgress extends javax.swing.JDialog {
    File[] files;
    Clusterizer clusterizer;
    /** Creates new form LinguisticProcessingProgress */
    public LinguisticProcessingProgress(java.awt.Frame parent, File[] files) {
        super(parent, true);
        this.files = files;
        initComponents();
        try {
            clusterizer = new Clusterizer();
        } catch (IOException e) {
            e.printStackTrace();            
        }
    }

    public ClusterizationResult[] getClusterization() {
        ArrayList<ClusterizationResult> clusterizationResults = new ArrayList<ClusterizationResult>();
        new Thread(){

            @Override
            public void run() {
                jProgressBar1.setMaximum(files.length);

                for (int i = 0; i < files.length; i++) {
                    File file = files[i];
                    jTextArea1.append(file.toString()+"...\n");
                    jTextArea1.append(clusterizer.getClusterizationResult(file).toString()+"\n");
                    jProgressBar1.setValue(i);
                }
                //setVisible(false);
            }

        }.start();
        setVisible(true);               
        return clusterizationResults.toArray(new ClusterizationResult[clusterizationResults.size()]);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
